import React from "react";
import Template from "./Template";
import * as pageFetchers from "@/lib/fetchers/pages";
import * as sectionFetchers from "@/lib/fetchers/sections";

import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Home Page",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const {
    data: { metadata },
  } = await pageFetchers.fetchPage({ pageId: "home" });

  if(!metadata) return {}

  return {
    title: metadata.metaTitle,
    description: metadata.metaDescription,
  };
}

export const revalidate = 60; // 1min
// export const dynamic = "force-dynamic";

export default async function Home() {
  const { data } = await sectionFetchers.fetchSection({ sectionId: "hero" });

  // const sectionData: Section = data;

  return <Template sectionData={data} />;
}
